### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by venkatarun95** [vitorenesduarte/avoidingproblems#13]
Could you please clarify the licence under which this code is released?

I am specifically interested in whether this can be used for research purposes.

Thanks

**Comment by vitorenesduarte** [comment]
Hi,
I haven't think about it (no experience in that).
What's your advice?

**Comment by venkatarun95** [comment]
Thanks for the prompt reply. I think you have three broad options
1. Release under GPL. This allows people to use your code in any manner as long as they release any modifications under the same licence. If it were me, I would choose this as it will encourage people to contribute to this project.
2. Release under Apache/MIT licence: Allows people to do pretty-much whatever they want with your code. This means it can be used by for-profit companies as well and they won't be obligated to publicly share their code. People may contribute code nevertheless.
3. Don't put any licence: People can only use your code if you explicitly allow them to. This gives you full control on the code but discourages contribution from other people.

If you go for options 1 or 2, I will almost definitely contribute because I need to do secure multi-party computation and the code looks very complete and well written. I intend to add the offline triple generation phase and a parser for circuits generated using the FairplayMP system.

To release code under a particular licence, you can simply add a 'LICENCE' file to the root directory in your repository containung the licence text (see below). You can also copy-paste the licence text in your REAMDE.md

Link to licences:
GPL: https://www.gnu.org/licenses/gpl.txt
MIT: https://opensource.org/licenses/MIT (sweet and simple)
Apache: http://directory.fsf.org/wiki/License:Apache2.0

Thanks

**Comment by vitorenesduarte** [comment]
Cool. Thank you for the very complete answer.
I'll follow your advice #14.

I can try to improve some things to adjust to your needs.
Maybe start by adding some tests (and configure Travis here on GitHub).
This was an academic project from two semesters ago, but I'll be glad to help keep this alive.

**Comment by venkatarun95** [comment]
Thanks!

I'll work on generating Beaver Triples without relying on a dealer.
